-- 第3周注释补丁：为已有表和字段补齐中文注释
-- 注意：该脚本不会重建表

SET NAMES utf8mb4;

ALTER TABLE users
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户主键ID',
    MODIFY COLUMN username VARCHAR(32) NOT NULL COMMENT '登录用户名（唯一）',
    MODIFY COLUMN password_hash VARCHAR(100) NOT NULL COMMENT '密码哈希（BCrypt）',
    MODIFY COLUMN nickname VARCHAR(64) NOT NULL COMMENT '用户昵称',
    MODIFY COLUMN phone VARCHAR(20) NULL COMMENT '手机号（可选）',
    MODIFY COLUMN avatar_url VARCHAR(255) NULL COMMENT '头像URL（可选）',
    MODIFY COLUMN role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER' COMMENT '用户角色',
    MODIFY COLUMN status ENUM('ACTIVE', 'BANNED') NOT NULL DEFAULT 'ACTIVE' COMMENT '账号状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '用户表';

ALTER TABLE orders
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单主键ID',
    MODIFY COLUMN requester_id BIGINT NOT NULL COMMENT '需求方用户ID',
    MODIFY COLUMN runner_id BIGINT NULL COMMENT '接单方用户ID',
    MODIFY COLUMN type ENUM('EXPRESS', 'FOOD', 'DELIVERY') NOT NULL COMMENT '订单类型',
    MODIFY COLUMN pickup_location VARCHAR(120) NOT NULL COMMENT '取货点',
    MODIFY COLUMN dropoff_location VARCHAR(120) NOT NULL COMMENT '送达点',
    MODIFY COLUMN expected_time DATETIME NOT NULL COMMENT '期望完成时间',
    MODIFY COLUMN reward_amount INT NOT NULL COMMENT '报酬金额（元）',
    MODIFY COLUMN contact_mode ENUM('IN_APP', 'PHONE') NOT NULL COMMENT '联系方式类型',
    MODIFY COLUMN contact_value VARCHAR(64) NULL COMMENT '联系方式值',
    MODIFY COLUMN remark VARCHAR(200) NULL COMMENT '备注信息',
    MODIFY COLUMN status ENUM('OPEN', 'ACCEPTED', 'IN_PROGRESS', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'EXPIRED') NOT NULL COMMENT '订单状态',
    MODIFY COLUMN cancelled_by ENUM('REQUESTER', 'RUNNER', 'ADMIN') NULL COMMENT '取消操作方',
    MODIFY COLUMN cancel_reason VARCHAR(200) NULL COMMENT '取消原因',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '订单主表';

ALTER TABLE order_status_logs
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '状态日志主键ID',
    MODIFY COLUMN order_id BIGINT NOT NULL COMMENT '关联订单ID',
    MODIFY COLUMN from_status ENUM('OPEN', 'ACCEPTED', 'IN_PROGRESS', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'EXPIRED') NULL COMMENT '变更前状态',
    MODIFY COLUMN to_status ENUM('OPEN', 'ACCEPTED', 'IN_PROGRESS', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'EXPIRED') NOT NULL COMMENT '变更后状态',
    MODIFY COLUMN operator_id BIGINT NOT NULL COMMENT '操作人用户ID',
    MODIFY COLUMN note VARCHAR(255) NULL COMMENT '状态变更备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT = '订单状态流转日志表';

ALTER TABLE runner_stats
    MODIFY COLUMN runner_id BIGINT NOT NULL COMMENT '跑腿员用户ID',
    MODIFY COLUMN active_orders_count INT NOT NULL DEFAULT 0 COMMENT '当前进行中订单数',
    MODIFY COLUMN daily_accept_count INT NOT NULL DEFAULT 0 COMMENT '当日接单数',
    MODIFY COLUMN daily_date DATE NOT NULL COMMENT '统计日期',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '跑腿员统计表';

-- 若 reviews 表存在，则补充其中文注释
SET @has_reviews_table := (
    SELECT COUNT(1)
    FROM information_schema.tables
    WHERE table_schema = DATABASE()
      AND table_name = 'reviews'
);

SET @sql_patch_reviews_comments := IF(
    @has_reviews_table = 1,
    'ALTER TABLE reviews
        MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT ''评价主键ID'',
        MODIFY COLUMN order_id BIGINT NOT NULL COMMENT ''关联订单ID（一单一评）'',
        MODIFY COLUMN reviewer_id BIGINT NOT NULL COMMENT ''评价人用户ID'',
        MODIFY COLUMN runner_id BIGINT NOT NULL COMMENT ''被评价跑腿员ID'',
        MODIFY COLUMN rating TINYINT NOT NULL COMMENT ''评分（1到5）'',
        MODIFY COLUMN tags JSON NULL COMMENT ''评价标签（JSON）'',
        MODIFY COLUMN content TEXT NULL COMMENT ''评价内容'',
        MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT ''创建时间'',
        COMMENT = ''订单评价表''',
    'SELECT 1'
);
PREPARE stmt_patch_reviews_comments FROM @sql_patch_reviews_comments;
EXECUTE stmt_patch_reviews_comments;
DEALLOCATE PREPARE stmt_patch_reviews_comments;

